### ISSUE TITLE
FlyPerms V2.0 Milestone!

### ISSUE THREAD

**Issue by benwoo1110** [benwoo1110/FlyPerms#2]
This issue will be used to track the progress of the upcoming FlyPerms v2.0!

### **Cool new features:**
- [x] Add support for placeholderAPI.
- [x] Add option auto-enable flying if teleported to a location in air. 
- [x] Add option to reset fly speed on world/gamemode change.
- [x] Add option to set the speed to reset fly speed to when above option is enabled.
- [x] Allow setting of single value for speed group.

### **Other changes:**
- [x] Reworked underlying fight manager and permission checking code.
- [x] Add ability to set fly speed with decimal numbers.
- [x] Better handling of ignored worlds, should now allow plugin to change fly ability. (if any)
- [x] Config option to disable FlyPerms placeholderAPI extension if needed.
- [x] Add javadocs

**Comment by benwoo1110** [comment]
Just got released ;) 
https://github.com/benwoo1110/FlyPerms/releases/tag/2.0.0
